#!/bin/bash
set -e

echo "🔧 Generating .env file from environment variables..."

cat > /app/.env << EOF
HOST=0.0.0.0
PORT=${PORT:-10000}
WORKING_DIR=/app/data/rag_storage
INPUT_DIR=/app/data/inputs

LIGHTRAG_KV_STORAGE=${LIGHTRAG_KV_STORAGE:-PGKVStorage}
LIGHTRAG_DOC_STATUS_STORAGE=${LIGHTRAG_DOC_STATUS_STORAGE:-PGDocStatusStorage}
LIGHTRAG_GRAPH_STORAGE=${LIGHTRAG_GRAPH_STORAGE:-PGGraphStorage}
LIGHTRAG_VECTOR_STORAGE=${LIGHTRAG_VECTOR_STORAGE:-PGVectorStorage}

POSTGRES_HOST=${POSTGRES_HOST}
POSTGRES_PORT=${POSTGRES_PORT:-5432}
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DATABASE=${POSTGRES_DATABASE}
POSTGRES_SSL_MODE=${POSTGRES_SSL_MODE:-require}
POSTGRES_MAX_CONNECTIONS=${POSTGRES_MAX_CONNECTIONS:-20}
POSTGRES_VECTOR_INDEX_TYPE=${POSTGRES_VECTOR_INDEX_TYPE:-HNSW}
POSTGRES_HNSW_M=${POSTGRES_HNSW_M:-32}
POSTGRES_HNSW_EF=${POSTGRES_HNSW_EF:-128}

LLM_BINDING=${LLM_BINDING:-openai}
LLM_MODEL=${LLM_MODEL:-gpt-5-mini}
LLM_BINDING_HOST=${LLM_BINDING_HOST}
LLM_BINDING_API_KEY=${LLM_BINDING_API_KEY}

EMBEDDING_BINDING=${EMBEDDING_BINDING:-openai}
EMBEDDING_MODEL=${EMBEDDING_MODEL}
EMBEDDING_DIM=${EMBEDDING_DIM:-1536}
EMBEDDING_BINDING_HOST=${EMBEDDING_BINDING_HOST}
EMBEDDING_BINDING_API_KEY=${EMBEDDING_BINDING_API_KEY}
EMBEDDING_BATCH_NUM=${EMBEDDING_BATCH_NUM:-100}
EMBEDDING_FUNC_MAX_ASYNC=${EMBEDDING_FUNC_MAX_ASYNC:-24}

MAX_ASYNC=${MAX_ASYNC:-8}
MAX_PARALLEL_INSERT=${MAX_PARALLEL_INSERT:-8}
MAX_GRAPH_NODES=${MAX_GRAPH_NODES:-30000}
FORCE_INIT_DB=${FORCE_INIT_DB:-True}
SUMMARY_LANGUAGE=${SUMMARY_LANGUAGE:-English}

ENTITY_TYPES='${ENTITY_TYPES}'

LIGHTRAG_API_KEY=${LIGHTRAG_API_KEY}
AUTH_ACCOUNTS="${AUTH_ACCOUNTS}"

VERBOSE_DEBUG=${VERBOSE_DEBUG:-False}
EOF

echo "✅ .env file created successfully"
echo "📝 Storage configuration:"
grep "LIGHTRAG.*STORAGE" /app/.env

echo ""
echo "🚀 Starting LightRAG server..."

# Start the server
exec python -m lightrag.api.lightrag_server --host 0.0.0.0 --port ${PORT:-10000}
